# Generated by Django 4.2.7 on 2023-11-16 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Costumer",
            fields=[
                ("costumer_id", models.AutoField(primary_key=True, serialize=False)),
                ("costumer_name", models.CharField(max_length=100)),
                ("costumer_family_name", models.CharField(max_length=100)),
                ("costumer_email", models.EmailField(max_length=70, unique=True)),
                ("costumer_phone", models.CharField(max_length=20)),
                ("customer_address", models.CharField(max_length=1000)),
                ("customer_postal_code", models.CharField(max_length=10, unique=True)),
                (
                    "costumer_created_at",
                    models.DateTimeField(verbose_name=datetime.datetime.now),
                ),
                ("costumer_updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
