# Generated by Django 4.2.7 on 2023-12-12 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('costumer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=70, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('costumer_updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
