# Generated by Django 4.2.7 on 2023-11-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("costumers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costumer",
            old_name="costumer_email",
            new_name="Email",
        ),
        migrations.RenameField(
            model_name="costumer",
            old_name="customer_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="costumer",
            old_name="costumer_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="costumer",
            old_name="costumer_family_name",
            new_name="family_name",
        ),
        migrations.RenameField(
            model_name="costumer",
            old_name="costumer_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="costumer",
            old_name="costumer_phone",
            new_name="phone",
        ),
        migrations.RenameField(
            model_name="costumer",
            old_name="customer_postal_code",
            new_name="postal_code",
        ),
    ]
