# Generated by Django 4.2.7 on 2023-12-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumers', '0001_initial'),
        ('products', '0016_comment_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('costumer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='costumers.costumer')),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
