# Generated by Django 4.2.7 on 2023-11-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costumers', '0002_rename_costumer_email_costumer_email_and_more'),
        ('products', '0009_rename_product_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('costumer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='costumers.costumer')),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
