# Generated by Django 4.2.7 on 2023-11-16 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField(max_length=2000)),
                (
                    "costumer_created_at",
                    models.DateTimeField(verbose_name=datetime.datetime.now),
                ),
                ("costumer_updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
