# Generated by Django 4.2.7 on 2023-11-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_comment_costumer_fid_comment_product_fid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="costumer_created_at",
            new_name="comment_created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="costumer_updated_at",
            new_name="comment_updated_at",
        ),
    ]
