# Generated by Django 4.2.7 on 2023-11-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "comments",
            "0003_rename_costumer_created_at_comment_comment_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment_text",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="costumer_Fid",
            new_name="costumer_id",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="comment_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="product_Fid",
            new_name="product_id",
        ),
    ]
