# Generated by Django 4.2.7 on 2023-12-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='pages/post_cover/', verbose_name='Post Image'),
        ),
    ]
