# Generated by Django 4.2.7 on 2024-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('family_name', models.CharField(blank=True, max_length=100)),
                ('Address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
