# Generated by Django 4.2.7 on 2023-11-26 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_rename_product_brand_product_brand_and_more'),
        ('costumers', '0002_rename_costumer_email_costumer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('comment_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('costumer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='costumers.costumer')),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
