# Generated by Django 4.2.7 on 2023-11-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("cost", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ghataat_badaneh", "ghataat_badaneh"),
                            ("motor_exoz", "motor_exoz"),
                            ("barghi_electricy", "barghi_electricy"),
                            ("roghan_filter", "roghan_filter"),
                            ("ghataat_dakheli", "ghataat_dakheli"),
                            ("enteghal_ghodrat", "enteghal_ghodrat"),
                            ("farman_jelobandi_tormoz", "farman_jelobandi_tormoz"),
                            ("bolboring", "bolboring"),
                            ("kasenamad", "kasenamad"),
                            ("oring", "oring"),
                            ("gardgir", "gardgir"),
                            ("looleh", "looleh"),
                            ("tasmeh", "tasmeh"),
                            ("shelang", "shelang"),
                        ],
                        max_length=40,
                    ),
                ),
            ],
        ),
    ]
