# Generated by Django 4.2.7 on 2023-11-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="brand",
            field=models.CharField(
                choices=[
                    ("saipa", "saipa"),
                    ("mashad_washer", "mashad_washer"),
                    ("HIC", "HIC"),
                    ("ezaam", "ezaam"),
                ],
                default="blank",
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
