# Generated by Django 4.2.7 on 2023-11-14 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_products_brand_products_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.ImageField(
                default="product_images/bolboring.jpg",
                height_field=600,
                upload_to="product_images/bolboring.jpg",
                width_field=600,
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="brand",
            field=models.CharField(
                choices=[
                    ("saipa", "saipa"),
                    ("mashad_washer", "mashad_washer"),
                    ("HIC", "HIC"),
                    ("ezaam", "ezaam"),
                ],
                default="blank",
                max_length=40,
            ),
        ),
    ]
