# Generated by Django 4.2.7 on 2023-11-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_products_created_at_products_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
