# Generated by Django 4.2.7 on 2023-11-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_products_image_alter_products_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
