# Generated by Django 4.2.7 on 2023-11-14 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_products_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
