# Generated by Django 4.2.7 on 2023-11-16 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_products_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=100)),
                ("product_cost", models.IntegerField()),
                (
                    "product_category",
                    models.CharField(
                        choices=[
                            ("ghataat_badaneh", "ghataat_badaneh"),
                            ("motor_exoz", "motor_exoz"),
                            ("barghi_electricy", "barghi_electricy"),
                            ("roghan_filter", "roghan_filter"),
                            ("ghataat_dakheli", "ghataat_dakheli"),
                            ("enteghal_ghodrat", "enteghal_ghodrat"),
                            ("farman_jelobandi_tormoz", "farman_jelobandi_tormoz"),
                            ("bolboring", "bolboring"),
                            ("kasenamad", "kasenamad"),
                            ("oring", "oring"),
                            ("gardgir", "gardgir"),
                            ("looleh", "looleh"),
                            ("tasmeh", "tasmeh"),
                            ("shelang", "shelang"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "product_brand",
                    models.CharField(
                        choices=[
                            ("saipa", "saipa"),
                            ("mashad_washer", "mashad_washer"),
                            ("HIC", "HIC"),
                            ("ezaam", "ezaam"),
                            ("crouse", "crouse"),
                            ("amirnia", "amirnia"),
                            ("jaham_lent", "jaham_lent"),
                            ("behran", "behran"),
                            ("isaco", "isaco"),
                        ],
                        default="blank",
                        max_length=40,
                    ),
                ),
                ("product_stock", models.IntegerField(default=0)),
                (
                    "product_created_at",
                    models.DateTimeField(verbose_name=datetime.datetime.now),
                ),
                ("product_updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Products",
        ),
    ]
