# Generated by Django 4.2.7 on 2023-11-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_delete_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_brand",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_cost",
            new_name="cost",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="product_stock",
            new_name="stock",
        ),
    ]
