# Generated by Django 4.2.7 on 2023-12-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_product_updated_at_product_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_status',
            new_name='status',
        ),
    ]
