# Generated by Django 4.2.7 on 2023-12-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_product_status_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
    ]
