# Generated by Django 4.2.7 on 2023-12-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='text',
        ),
    ]
