# Generated by Django 4.2.7 on 2023-12-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_body_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.CharField(choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Very Good')], default=5, max_length=10),
        ),
    ]
