# Generated by Django 4.2.7 on 2023-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_comment_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('saipa', 'سایپا'), ('mashad_washer', 'مشهد واشر'), ('HIC', 'اچ آی سی'), ('ezaam', 'عظام'), ('crouse', 'کروز'), ('amirnia', 'امیرنیا'), ('jahan_lent', 'جهان لنت'), ('behran', 'بهران'), ('isaco', 'ایساکو')], default='blank', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ghataat_badaneh', 'بدنه'), ('motor_exoz', 'موتور_اگزوز'), ('barghi_electricy', 'برقی_الکتریکی'), ('roghan_filter', 'روغن_فیلتر'), ('ghataat_dakheli', 'قطعات داخلی'), ('enteghal_ghodrat', 'انتقال قدرت'), ('farman_jelobandi_tormoz', 'فرمان_جلوبندی_ترمز'), ('bolboring', 'بولبورینگ'), ('kasenamad', 'کاسه نمد'), ('oring', 'اورینگ'), ('gardgir', 'گردگیر'), ('looleh', 'لوله'), ('tasmeh', 'تسمه'), ('shelang', 'شلنگ')], max_length=40),
        ),
    ]
