# Generated by Django 4.2.7 on 2023-12-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_rename_cost_product_price_alter_comment_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='products/product_cover/', verbose_name='Product Image'),
        ),
    ]
