# Generated by Django 4.2.7 on 2023-12-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
