# Generated by Django 4.2.7 on 2023-12-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_rename_product_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='car_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
