# Generated by Django 4.2.7 on 2023-12-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_category_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='car_type',
        ),
    ]
