# Generated by Django 4.2.7 on 2023-12-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='tags',
        ),
    ]
