# Generated by Django 4.2.7 on 2023-12-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_rename_category_product_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
    ]
